### ISSUE TITLE
Interpreting beta coefficients for binary co-variates

### ISSUE THREAD

**Issue by mnadim01** [bryandmartin/corncob#120]
Hi Bryan,

I realize this might be a bit of a repeat of Jacob’s question in 2019, but I’m still confused about this. I am interested in the impact of a treatment (yes/no) on the differential abundance of bacterial taxa. For each significant taxa identified by the DifferentialTest function, I had been interpreting the beta co-efficient as the log2 fold change in relative abundance among treatment subjects relative to control subjects. However, I’m realizing that might not be correct!

If not, how should I be interpreting the B coefficients for these taxa, and is it possible to use them to calculate fold change between treatment and controls? I notice a lot of clinical trials only report taxa that have at least 4-fold difference between treatment and control subjects, so I’d like to be able to compare.

Thank you!
Maya

**Comment by bryandmartin** [comment]
Hi @mnadim01 ,

It's not the log2 fold change, because corncob uses the logit link, not the log2 link. You can interpret these similarly as you might with logistic regression. corncob is a hierarchical model, and we didn't want to link covariates with something like a log2 link to the observed counts. The logit link allows the model to use count information to conduct inference about a parameter describing the underlying compositional population.

That being said, if you wanted to do something, one option would be to calculate the expected observed counts. It's not quite the same as the log2 fold change however.

Hope this helps, but please let me know if you have any follow up questions!

Bryan
