### ISSUE TITLE
N/A P-Values 

### ISSUE THREAD

**Issue by Desorcy91** [bryandmartin/corncob#138]
Hello, 

When using code : 

"Week1corncob$p_fdr[1:23]"

I get several adjusted p-values but also several N/A's. Does this mean that they aren't p<.05 after adjustment? "Week1corncob" is my object. If anyone knows I'd appreciate it. 

Thanks,

Katelyn

**Comment by adw96** [comment]
Hi Katelyn! 

> I get several adjusted p-values but also several N/A's. Does this mean that they aren't p<.05 after adjustment?

No, that's not what this means. You will notice that `Week1corncob$p[1:23]` has NA's in the same place. 

Taxa with NA's are "discriminant taxa" -- taxa that are observed in one group only. Unfortunately we can't run a hypothesis test for these taxa, but I certainly wouldn't discard them, because the are clearly strongly associated with one group. 

I hope that helps!
