### ISSUE TITLE
p-values between differentialTest() and bbdml() 

### ISSUE THREAD

**Issue by cyklee** [bryandmartin/corncob#26]
Hi, thank you for developing corncob. 
As I was going through the vignette, I tried to look at the direction of the differential abundance of the taxa by putting them through `bbdml()` individually (as an attempt to bypass #15 ). I noticed that OTU.19 was reported as a significant taxa:

```
otu_to_taxonomy(OTU = da_analysis$significant_taxa, data = soil)

      OTU.19  
3.323423e-03
````

However, when I put it through `bbdml()`:

```
test <- bbdml(formula = OTU.19 ~ DayAmdmt,
      phi.formula = ~ DayAmdmt,
      data = soil)

summary(test)

Call:
bbdml(formula = OTU.19 ~ DayAmdmt, phi.formula = ~DayAmdmt, data = soil)

Coefficients:
                Estimate Std. Error t value Pr(>|t|)    
mu.(Intercept)  -1.64987    0.04930 -33.467  < 2e-16 ***
mu.DayAmdmt21    0.02926    0.05321   0.550  0.58672    <-- ?
phi.(Intercept) -5.24564    0.35403 -14.817 8.87e-15 ***
phi.DayAmdmt21  -1.79881    0.50455  -3.565  0.00133 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Log-likelihood: -281.05
```

It appears I've got a non-significant result. This raises the question:

1. Shouldn't differentialTest() be more stringent due to FDR correction? (As seen for OTU.4206 in the vignette).
2. Could I still use the coefficient 0.02926 to say that OTU.19 is differentially more abundant in DayAmdmt21?

Thanks again for your time

Kevin

**Comment by bryandmartin** [comment]
Hi Kevin,

Thanks for documenting this. I haven't been able to reproduce your differentialTest results. Could you try redownloading corncob and letting me know if you still getting this issue? I do get significance when testing for differential variability, but not differential abundance.

In response to your questions:

1. In general, yes. I will note though that the summary function uses a t-test, and differentialTest uses a z-test, so there may be slight differences due to that.
2. Given the p-value, I don't think I would want to reject the null hypothesis that the abundances are equal across DayAmdmt, but differentialTest should agree with this. Let me know if it doesn't.

Thanks again,
Bryan

**Comment by cyklee** [comment]
Hi Bryan,

I've updated corncob and gave it another try. It seems the problem has gone away now.
With `differentialTest()` now I get p=5.823610e-01 and p.fdr=7.629909e-01 for OTU.19 and with `bbdml()` I get p=5.87e-01 for coefficients associated with abundance (yay new interface!), so as you said, different tests but not too far off. In short, everything seems to work as intended now.

Thanks!

**Comment by bryandmartin** [comment]
Great, thank you! 

P.S. I'm glad you like the new interface. I've also (literally just now) pushed an update completing all the documentation and adding examples for every function. In the next few days I'll be working on creating new vignettes and tutorials. Thanks for posting this, and let me know if you encounter any more issues or have any more questions!
