### ISSUE TITLE
Unable to identify Differentially abundant or variable taxa?

### ISSUE THREAD

**Issue by nmshahir** [bryandmartin/corncob#28]
So I'm going through the vignette for corncob and for some reason calling
$DV or $DA on the results of differentialTest is not possible?
Has that been removed or?

Best,
N

**Comment by bryandmartin** [comment]
Hi N,

Thank you for logging this issue. Yes, this has been updated to improve the generalizability of differentialTest. The new vignette reflects these updates. Please let me know if you have further issues!

Bryan

**Comment by bryandmartin** [comment]
Hi Jill,

I don't get this issue. Are you using `devtools::install_github("bryandmartin/corncob", build_vignettes = TRUE)` (from the Use section) rather than `devtools::install_github("bryandmartin/corncob")` (from the Installation section)?

This vignette is also a bit old. Now that I've completed documentation and pushed some major updates, I'm going to work on new tutorials. I'll let you know when they are done! In the meantime, any new features that aren't explained there should be fully explained in the documentation (or let me know if they are not!).

Bryan

**Comment by jvhagey** [comment]
Yes, using the following I get an error.
`>devtools::install_github("bryandmartin/corncob", build_vignettes = TRUE, force=TRUE)`
`>utils::browseVignettes(package = "corncob")'
'No vignettes found by utils::browseVignettes(package = "corncob")'

When I look in the folder ./corncob/Meta/ in my R library folder there is no vignette.rds file like other programs have. By "Documentation" did you just mean the reading the vignette on github rather than trying to load it via R or is there another place with more details? Since you are currently updating the vignette I'll just hang tight and have a look at the new one when it comes out. 

I did have a question about the vignette on github. The data in the vignette had categorical variables for Amdmt and Day, but the vignette uses the combined DayAmdmt variable in the model. Is this how you recommend incorporating repeated measures into the model or was this just for ease/speed for the tutorial?

**Comment by bryandmartin** [comment]
Hi @jvhagey ,

I'm not sure what was causing this issue before, but there is now a new vignette. Could you try re-downloading and see if it is still an issue? When I run those lines it loads fine for me now, though it did before as well, so I'd like to make sure this gets resolved.

To answer your other question, DayAmdmt was mostly created as an easy way to filter a subset of the data on specific Day/Amdmt combinations. In general, it depends on what I want to compare. If I want to compare Day 1 Amdmt 1 to Day 2 Amdmt 2, I would combine them. If I want to see the effect of going from Amdmt 1 to Amdmt 2, controlling for Day, I would not combine them. This isn't specific to corncob, I'd make the same choices as I would when modeling any categorical data.

Bryan

**Comment by bryandmartin** [comment]
Yes, that's almost certainly it. The vignette requires phyloseq. Thanks for posting the output!

Could you try downloading phyloseq and letting me know if the issue still occurs?

**Comment by jvhagey** [comment]
I have phyloseq already downloaded. I also tried calling the library before installing and still got the same result.
```
PackageVersion("phyloseq")
[1] ‘1.24.2’
```

**Comment by jvhagey** [comment]
Your suggestion did fix the phyloseq issue, but I still had the same error of the vignette not being found. However, I found the problem and a fix!

Turns out there was a change with the devtools with version >= 2.0.0 ( I am using 2.0.1) and there is no longer a `build_vignettes = TRUE` option so you have use the change below to make it build the vignette. 
https://community.rstudio.com/t/vignettes-suddenly-stopped-installing/18391/2

```
if (!requireNamespace("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
> devtools::install_github("bryandmartin/corncob", build=TRUE, build_opts = c("--no-resave-data", "--no-manual"), repos=BiocInstaller::biocinstallRepos(), dependencies=TRUE, type="source", force=TRUE)
Downloading GitHub repo bryandmartin/corncob@master
√  checking for file 'C:\Users\Jill\AppData\Local\Temp\Rtmp0mHBDb\remotesab84e7223ef\bryandmartin-corncob-ff3e86d/DESCRIPTION' ... 
-  preparing 'corncob': (714ms)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes (1.2s)
√  creating vignettes (6m 7.3s)
-  checking for LF line-endings in source and make files and shell scripts (826ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'corncob_0.1.0.tar.gz'
```
Now it works! Thanks for the help!

**Comment by bryandmartin** [comment]
Excellent, thanks for working through this! I'll update the Readme to reflect the changes to devtools.
