### ISSUE TITLE
Handling taxa/OTUs which have singular Hessian matrices? 

### ISSUE THREAD

**Issue by JacobRPrice** [bryandmartin/corncob#69]
I'm exploring the output from differentialTest() and I've observed that, for a small number of taxa, the coefficients table isn't fully populated. More specifically, it returns "Estimate" values for each of the terms, but does not populate the "Std. Error", "t value", or "pvalue" fields. For example: this is the output for one of my OTUs: 

![Screen Shot 2019-09-11 at 1 10 52 PM](https://user-images.githubusercontent.com/11934394/64723191-a120ae80-d495-11e9-958f-50de53519111.png)

Applying bbdml() to just the single taxa and then passing the output to waldt() reveals that the issue is due to a singlular Hessian matrix. In this case, waldt() will still create the coefficients table, but that table will only have values for the Estimates. 

![Screen Shot 2019-09-11 at 1 31 50 PM](https://user-images.githubusercontent.com/11934394/64724788-cc58cd00-d498-11e9-8c91-71332de03b10.png)

NOTE: I'm working with a *very* small dataset (in terms of read counts), so it might just be the particular material I'm working with, with much larger (more realistic) read counts there may be less of a chance of encountering this issue. 

I thought I'd bring this to @bryandmartin and @adw96's attention. 

I don't know if there's a way to get around the non-invertable matrix problem ([possibly?](https://gking.harvard.edu/files/help.pdf)) but I would encourage the developers to include in the documentation and/or error/warning message a discussion/information about what this output means.

**Comment by adw96** [comment]
Hey @bryandmartin can you look into this ASAP please?

**Comment by adw96** [comment]
@JacobRPrice can you please provide us the input data that you used to get these results? We need the M and W values to replicate it.

**Comment by bryandmartin** [comment]
Hi @JacobRPrice ,

Happy to investigate this specific case further if given input data, but this is done by design. In certain cases (most commonly, all zero counts in some experimental group) it is impossible to invert the Hessian, and thus impossible to conduct a Wald hypothesis test. Perhaps there are emerging alternatives such as the link you provided which uses a pseudo-variance matrix, but I wouldn't feel comfortable including this in corncob without it being fully tested (such as the other methods were in the publication) so that the implications on hypothesis testing can be more fully understood. 

That being said, I am very comfortable saying something I know to be true, such as "For this taxon in this data, you do not have sufficient data to conduct a valid Wald hypothesis test. Therefore, we recommend either using a likelihood ratio test, or omitting this taxon from your analysis". Personally, I'd like to examine this data on a case-by-case basis, and try to fully understand why the error is occurring before making a decision that changes my hypothesis testing. If it only occurred in a few taxa that aren't of particular interest, I would probably chose to omit them.

Feel free to reach out if you have further questions, or if this answers them, please close the issue.

Thanks!
Bryan

**Comment by JacobRPrice** [comment]
Hi @bryandmartin, 

@adw96 and I ended up speaking a bit offline. Her thoughts were that this behavior could be the result of a couple of factors: 
1) singular Hessian matrices like I noted in the OP and you discuss in your response, 
2) a taxa is only observed in one sample, or group of samples,  like you mentioned 
3) perfectly linear covariates 

I'm glad to hear that this behavior is intentional. I do see that you mention a taxa only occurring in one sample in the vignette. It might be worth considering expanding that portion of the vignette to include a little more detail, or maybe the function's documentation. 

I'll close the issue. 

For posterity, here is an example dataset:
[example_ps.RDS.zip](https://github.com/bryandmartin/corncob/files/3691589/example_ps.RDS.zip)
And here is a reproducible example of what I'm seeing.

```
sapply(c("phyloseq", "corncob"), require, character = TRUE)
example_ps <- readRDS(file = "/change/this/file/path/to/downloaded/file")
example_dT <- differentialTest(
  example_ps,
  formula = ~ reactor.cat,
  phi.formula = ~ reactor.cat,
  formula_null = ~ 1,
  phi.formula_null = ~ reactor.cat,
  test = "Wald",
  boot = FALSE
)

# which of the taxa do not have p values
unname(which(is.na(example_dT$p)))
# the same taxa don't contain entries for Std. Error in [["coefficients"]]
which(
  lapply(example_dT[["all_models"]], function(i) {
    NA %in% i[["coefficients"]][,2] }) == TRUE 
  )
# look at taxa 3 individually
test_3 <- bbdml(
  formula = ACGTGCGTTATTCATACAACCTGGGCGTAAAGCGTCTTTAGGCGGTTCTTCGTGTGTTAGCACCTAAAAACCAGAACGTAATTCTGGAAAGTTTGCTAAAACTGTTTTTCTCGAGTTTATGAGGGGTTAGTAGTATTTCTCTATGAGGGTTAAAATTCTTAGATAGGAGAGAGAGGTCCATCGGTGAAGACAACTAACTAGCATTAACTGACGCCAAAGGACTAAAGCATAGGGAGCGATAGGGATTAGATACCCCTGTAGTCTATGCCTTGACTAATGAAAGTGAAACGTTGGAGCGTTCCAACTGTTGCAGCTAACGCGTGGAACTTTCCGCCTGAGGAGTACGGT ~ reactor.cat,
  phi.formula = ~ reactor.cat,
  data = example_ps
)
# still not returning Std Error, t stat, or p-value
summary(test_3)

# is taxa only seen in one sample OR group of samples? 
cbind(count = as.vector(otu_table(example_ps)[,3]),
      as.data.frame(sample_data(example_ps)))
# no, taxa 3 is seen in both reactors...

# singular Hessian? 
corncob::waldt(test_3)
# yup, that's the hangup...
```
