### ISSUE TITLE
plot.bbdml - reorder functionality can break if factor levels begin with numerals

### ISSUE THREAD

**Issue by gzahn** [bryandmartin/corncob#80]
Just a note:
If you want to use color, shape, etc. in your plot, factors with numerals in them can break the reordering functionality.

# reorder
  my_ord_str <- paste(my_ord_str, df$samples, sep = "_")
  df$order <- factor(df$samples, levels = df$samples[order(my_ord_str)])

as an example, I tried to color by a grouped temperature:
levels(ps@samdata$tempgroup)
Levels: <30.5 30.5-31 >31

The plot.bbdml function kept splitting these groups in the final plot. I fixed temporarily by appending "A","B","C" to the start of those groups.

**Comment by bryandmartin** [comment]
Hey @gzahn ,

Thanks for posting this issue, this is great to know! Glad you were able to get a workaround going. I'll update this and close the issue when it's incorporated.

**Comment by gzahn** [comment]
Great!
Just FYI, this is a really great set of tools. Excellent work!

**Comment by bryandmartin** [comment]
Hi @gzahn,

Thanks again for your patience on this. Now when I tried this in a test case, I got the ordering following the default ordering of factors in R, in this case: "< 30.5", then "> 31", then "30.5 - 31".

The first thing to make sure is that your factor ordering in R matches the order you would like it to appear in. I would like for the function to plot by factor level. If you want to specify a factor level, that to me is a data cleaning task. For example, I tried setting: 

`sample_data(tmp)$temp <- sample_data(tmp)$temp %>%
  forcats::fct_relevel(levels = c("< 30.5", "30.5 - 31", "> 31"))`
where `tmp` is my data set and `temp` is my temperature sample data. 

Assuming you already did that though, I am now pushing an update that will plot them in the correct order! This issue will close automatically when the update is complete, so let me know if you have any further issues with factor levels after this issue is closed and you re-download the package!

Bryan

**Comment by gzahn** [comment]
Yes, it was splitting one of my groups (see attached fig.)
To get around the re-ordering I had to change the factor levels to include
a letter in front:

ps@sam_data$AvgSiteTempGroup <- factor(ps@sam_data$AvgSiteTempGroup,
                                       levels =
c("A_<30.5","B_30.5-31","C_>31"))

That tricked it into working.
I'm looking at the code diff and having it order by factor level should fix
the issue.  Thanks!!

Geoff


[image: image.png]

**Comment by bryandmartin** [comment]
No problem! The updated code has been pushed, so as long as the factor is ordered correctly it should work fine for you. Let me know if you have any issues.
